### ISSUE TITLE
MAIN_LOOP_DELAY is not defined

### ISSUE THREAD

**Issue by ategus** [inofix/lifebase-meter#11]
**behavior:**
Compile Error in IDE

![Error Message Arduino IDE](https://user-images.githubusercontent.com/5208864/84399778-88e6e700-ac01-11ea-8769-169c8bf09b48.png)

**steps to reproduce:**

use this config and compile in Arduino IDE
[lifebase-meter-RonnyTestMoisture.zip](https://github.com/inofix/lifebase-meter/files/4765491/lifebase-meter-RonnyTestMoisture.zip)

try to fix

- set the value to 1:

#define MAIN_LOOP_DELAY 1

Code does compile but after flashing i got the error message in the serial monitor:

![Bildschirmfoto von 2020-06-11 16-39-10](https://user-images.githubusercontent.com/5208864/84400275-1fb3a380-ac02-11ea-8fda-70d3175c5af1.png)

error message
Backtrace: 0x4000c2e0:0x3ffc8570 0x400d5af2:0x3ffc8580 0x400d52b6:0x3ffc85d0 0x400d53da:0x3ffc8640 0x400d1c86:0x3ffc86a0 0x400d7c1b:0x3ffc8700 0x4008e089:0x3ffc8720

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x4000c2e0  PS      : 0x00060330  A0      : 0x800d5af5  A1      : 0x3ffc8570  
A2      : 0x3ffc8580  A3      : 0x00000000  A4      : 0x00000012  A5      : 0x3ffc8580  
A6      : 0x00000001  A7      : 0x00000001  A8      : 0x00000000  A9      : 0x00000000  
A10     : 0x3ffc859c  A11     : 0x3ffc8594  A12     : 0x3ffdd349  A13     : 0x3ffdd33c  
A14     : 0x3ffdd428  A15     : 0xff000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  

Backtrace: 0x4000c2e0:0x3ffc8570 0x400d5af2:0x3ffc8580 0x400d52b6:0x3ffc85d0 0x400d53da:0x3ffc8640 0x400d1c86:0x3ffc86a0 0x400d7c1b:0x3ffc8700 0x4008e089:0x3ffc8720

**Comment by zwischenloesung** [comment]
Thanks for your interest and this report!

The documentation was actually very bad, the missing part was thus not really in the code but in my very bad instructions...

Some values are not defined as I need persistent custom programs for my devices. The errors come from missing UUIDs expected by BLE and what we need to distinguish the devices.

I have updated the README to explain all steps needed to have a running project in the arduino IDE, please go to [Running the Code](https://github.com/inofix/lifebase-meter#running-the-code).

I will leave the ticket open for now, please close it when you find the instructions clear enough to be helpful.
